세션/1.16/Piro20_django/server/apps/local_users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('list/', user_list, name='list'),
    path('create/', create, name ='create'),
    path('delete/<int:pk>/', delete, name="delete"),
    path('update/<int:pk>/', update, name='update'),
]

세션/1.16/Piro20_django/server/apps/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name ='create'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name="delete"),
    path('update/<int:pk>/', update, name='update'),
]

세션/1.16/Piro20_django/server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('users/', include('apps.local_users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

세션/1.16/Piro20_django/server/apps/local_users/models.py
from django.db import models

class LocalUser(models.Model):
    name = models.CharField('이름', max_length=24)
    age = models.IntegerField('나이', default=20)
    
    def __str__(self):
        return self.name

세션/1.16/Piro20_django/server/apps/posts/models.py
from django.db import models
from apps.local_users.models import LocalUser

# Create your models here.
class Post(models.Model):
    title = models.CharField('제목', max_length=24)
    content = models.CharField('내용', max_length=24)
    region = models.CharField('지역', max_length=24)
    #작성자
    user = models.ForeignKey(LocalUser, on_delete=models.CASCADE, verbose_name='작성자')
    price = models.IntegerField('가격', default = 1000)
    #이미지
    photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
    #생성시각 , 수정시각
    created_date = models.DateTimeField('작성일', auto_created = True, auto_now_add = True)
    updated_date = models.DateTimeField('수정일', auto_created=True, auto_now=True)
    
    # admin에서 보여지는 str 
    def __str__(self):
        return f'[상품] {self.title}'

세션/1.16/Piro20_django/server/apps/local_users/forms.py
from django import forms
from .models import LocalUser

class LocalForm(forms.ModelForm):
    class Meta():
        model = LocalUser
        fields = ('__all__')

세션/1.16/Piro20_django/server/apps/local_users/views.py
from django.shortcuts import render, redirect
from .models import LocalUser
from .forms import LocalForm

# Create your views here.
def user_list(request):
    search_txt = request.GET.get('search_txt')
    users = LocalUser.objects.all()
    if search_txt:
        users = users.filter(name__contains = search_txt)
    ctx = {'users' : users}
    return render(request, 'users/user_list.html', ctx)

def create(request):
    if request.method == 'GET':
        form = LocalForm()
        ctx = {'form' : form}
        return render(request, 'users/user_create.html', ctx)

    form = LocalForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('users:list')

def delete(request,pk):
    if request.method == 'POST':
        LocalUser.objects.get(id=pk).delete()
    return redirect('users:list')

def update(request,pk):
    user = LocalUser.objects.get(id=pk)
    if request.method == 'GET':
        form = LocalForm(instance=user)
        ctx = {'form': form, 'pk': pk}
        return render(request, 'users/user_update.html', ctx)
    form = LocalForm(request.POST, instance=user)
    if form.is_valid():
        form.save()
    return redirect('users:list') #users:list는 pk를 안받음. 내가 억지로 pk 보내니까 오류남

세션/1.16/Piro20_django/server/apps/posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import Post

# Create your views here.
def main(request) :
    #쿼리스트링 가져오기
    search_txt = request.GET.get('search_txt')
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    
    posts = Post.objects.all() #select * from posts_posts; 
    #필터링
    if search_txt:
        posts = posts.filter(title__contains = search_txt)
    if min_price:
        posts = posts.filter(price__gt = min_price)
    if max_price:
        posts = posts.filter(price__lt = max_price)
        
    ctx = {'posts' : posts}
    return render(request, 'posts/post_list.html', ctx)

def create(request) :
    if request.method == 'GET':
        form = PostForm()
        ctx = {'form': form}
        return render(request, 'posts/post_create.html', ctx)
    #post일때 작동하는 코드
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
    return redirect('posts:main')

def detail(request, pk):
    post = Post.objects.get(id=pk)
    user = post.user
    related_posts = user.post_set.all()
    ctx = {'post' : post, 'related_posts': related_posts}
    return render(request, 'posts/post_detail.html', ctx)

def delete(request, pk):
    if request.method == 'POST':
        #pk에 해당하는 Post객체 조회하는 방법
        #posts = Post.objects.get(id=pk)
        #posts.delete()
        Post.objects.get(id=pk).delete()
    return redirect('posts:main')

def update(request, pk):
    post = Post.objects.get(id=pk)
    if request.method == 'GET':
        form = PostForm(instance=post)
        ctx = {'form': form, 'pk': pk}
        return render(request, 'posts/post_update.html', ctx)
    form = PostForm(request.POST, request.FILES, instance=post)
    if form.is_valid():
        form.save()
    return redirect('posts:detail', pk)

세션/1.16/Piro20_django/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="{%static 'posts/css/style.css'%}">  
  {%block head%}


  {% endblock %}
</head>
<body>
  <main>
    <a href="/" id='logo' style='text-decoration: none; color: red;'><h1>🍎 사과 마켓 🍎</h1></a>
    <hr>
    {%block content%}
      
    
    {%endblock%}
  </main>
  <footer>
    <a href="{% url 'users:create' %}" class="mx-2">
      <button type="button" class="btn btn-info">사용자 추가</button>
    </a>
    <a href="{% url 'users:list' %}" class="mx-2">
      <button type="button" class="btn btn-warning">사용자 관리</button>
    </a>
  </footer>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
</body>
</html>

세션/1.16/Piro20_django/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 style="color: green; font-size: 40px">{{post.title}}</h1>
  {% if post.photo.url != '' %}
    <img src="{{post.photo.url}}" alt="제품 이미지" />
  {% else %}
    <img src="{% static 'posts/image/no_img.png' %}" alt="대체 텍스트" />
  {% endif %}
  <p>작성자: {{post.user.name}}</p>
  <p>나이: {{post.user.age}}</p>
  <p>지역: {{post.region}}</p>
  <p>가격: {{post.price}}</p>
  <h2 class="my-3">{{post.content}}</h2>
  <p>작성일: {{post.created_date}}</p>
  <p>수정일: {{post.updated_date}}</p>
  <p>이 작성자의 글</p>
  {% for rel_post in related_posts %}
    <a href="{% url 'posts:detail' rel_post.pk %}" class="btn btn-success">
      {{rel_post.title}}
    </a>
  {% endfor %}

  <hr />
  <form action="{% url 'posts:delete' post.pk %}" method="POST">
    {%csrf_token%}
    <a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">수정하기</a>
    <button type="submit" class="btn btn-danger">삭제하기</button>
  </form>
{% endblock content %}

세션/1.16/Piro20_django/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>사과 마켓</title>
{%endblock%}

{%block content%}
  <div class="search-box">    
    <form action="/">      
      <input class = 'form-control mx-2' type="input" name="search_txt" placeholder="검색어..." />
      <input class = 'form-control mx-2' type="text" name="min_price" placeholder="최소 가격" />
      <input class = 'form-control mx-2' type="text" name="max_price" placeholder="최대 가격" />
      <input class = 'btn btn-outline-success mx-2' type="submit" value="검색" />      
    </form>
    <a href="{% url 'posts:create' %}" class = 'btn btn-secondary mx-2'>글 생성</a>
  </div>

  <div class="content-wrapper">
    <!-- 글 목록 -->
    {% for post in posts%}
    <div class="item">
      {% if post.photo.url != null and post.photo.url != ''%}
      <img src="{{post.photo.url}}" alt="대체텍스트"> 
      {%else %}
      <img src="{% static 'posts/image/no_img.png'%}" alt="대체텍스트"> 
      {%endif%}
      <div class="info">
        <a href="{% url 'posts:detail' post.pk %}" class="title">
          {{post.title}}
        </a>
        <p class="region">지역: {{post.region}}</p>
        <p class="price">가격: {{post.price}}</p>
        <p class="create-date">작성일: {{post.created_date}}</p>
        <p class="update-date">업뎃일: {{post.updated_date}}</p>
      </div>
    </div>
    {% endfor %}
  </div>
{%endblock%}

세션/1.16/Piro20_django/templates/posts/post_update.html
{% extends 'base.html' %}

{%block head %}
  <title>post_detail</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'posts:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
{%endblock%}

세션/1.16/Piro20_django/templates/users/user_create.html
{% extends 'base.html' %}
{%block head%}
  <title>post_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'users:create' %}"
    method="post"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">추가하기</button>
  </form>
{%endblock%}

세션/1.16/Piro20_django/templates/users/user_list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>사과 마켓</title>
{%endblock%}

{%block content%}
  <div class="search-box">    
    <form action="">      
      <input class = 'form-control mx-2' type="input" name="search_txt" placeholder="검색어..." />
      <input class = 'btn btn-outline-success mx-2' type="submit" value="검색" />
    </form>
  </div>

  <div class="content-wrapper">
    <!-- 사용자 목록 -->
    {% for user in users %}
    <div class="mb-3">
      <a href="{% url 'users:update' user.pk %}">
        <button type="button" class="btn btn-outline-secondary">
          <span>이름: {{ user.name }}</span>
          <span>나이: {{ user.age }}</span>
        </button>
      </a>
    </div>
    {% endfor %}
  </div>
{%endblock%}

세션/1.16/Piro20_django/templates/users/user_update.html
{% extends 'base.html' %}
{%block head %}
  <title>post_detail</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'users:update' pk %}"
    method="post"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
  <hr>
  <form
    action="{% url 'users:delete' pk %}"
    method="post"
  >
    {%csrf_token%}
    <button class="btn btn-danger">삭제</button>
  </form>
{%endblock%}