세션/1.13/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

세션/1.13/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.main, name="main"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

세션/1.13/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    GENDER_CHOICE = [
        ('Male', '남자'),
        ('Female', '여자'),
    ]
    JOB_CHOICE = [
        ('Student', '학생'),
        ('JobSeeker', '취준생'),
        ('Worker', '직장인'),
        ('Etc', '기타'),
    ]
    first_name = None
    last_name = None
    name = models.CharField(max_length=10, null=True)
    email = models.EmailField()
    nickname = models.CharField(max_length=20, null=True)
    birth = models.DateField(null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICE, null=True)
    job = models.CharField(max_length=10, choices=JOB_CHOICE, null=True)
    desc = models.TextField(max_length=100,blank=True, null=True)

세션/1.13/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignupForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    email = forms.CharField(
        label='이메일',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    nickname = forms.CharField(
        label='닉네임',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    gender = forms.ChoiceField(
        label='성별',
        choices=[('', '-----')] + User.GENDER_CHOICE,
        widget=forms.Select(
            attrs={
                'class': 'signup-input'
            }
        )
    )
    job = forms.ChoiceField(
        label='직업',
        choices=[('', '-----')] + User.JOB_CHOICE,
        widget=forms.Select(
            attrs={
                'class': 'signup-input'
            }
        )
    )
    birth = forms.CharField(
        label='생일',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    desc = forms.CharField(
        label='설명',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'name', 'nickname', 'gender', 'job', 'birth', 'desc']

세션/1.13/users/views.py
from django.shortcuts import render, redirect
from users.forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth

#app_name = users여서 경로가 users/main.html이됨
def main(request):
    return render(request, "users/main.html")

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)      
            return redirect('users:main')
        else:
            ctx= {
                'form':form,
            }
            return render(request, 'users/signup.html', context=ctx)
    else:
        form = SignupForm()
        context = {
            'form': form,
        }
        return render(request, template_name='users/signup.html', context=context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('users:main')
        else:
            context = {
                "forms": form,
            }
            return render(request, template_name="users/login.html", context=context)
    else:
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, template_name='users/login.html', context=context)
    
def logout(request):
    auth.logout(request)
    return redirect('users:main')

세션/1.13/templates/users/login.html
{%extends 'users/main.html' %}

{%block content%}
<form method="POST" action="">
    {%csrf_token%}
    {{form}}
    <button>Login</button>
</form>
{% endblock content%}

세션/1.13/templates/users/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/login.css' %}">
        <script defer src="{% static 'js/script.js' %}"></script>
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <li><a href="{% url 'users:logout' %}">Logout</a></li>    
        {% else %}
            <li><a href="{% url 'users:login' %}">Login</a></li>
            <li><a href="{% url 'users:signup' %}">Signup</a></li>
        {% endif %}

        {% block content %}
        {% endblock content %}
    </body>
</html>

세션/1.13/templates/users/signup.html
{% extends 'users/main.html' %}

{% block content %}
<div class="Flex_cc">
    <form method="POST" action="" id="signup1">
        {% csrf_token %}
        {{ form }}
        <div class="container">
            <input class="signup1-btn nice-effect" type="submit" value="회원가입">
            <div class="overlay"></div>
        </div>
    </form>
</div>
{% endblock content %}