myMovieReviews/review/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', review_list),
    path('<int:pk>', review_read),
    path('create', review_create),
    path('<int:pk>/update', review_update),
    path('<int:pk>/delete', review_delete),
]

myMovieReviews/review/models.py
from django.db import models

# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=32)
    year = models.CharField(max_length=32)
    GENRE_CHOICES = (
    ("action", "액션"),
    ("comedy", "코미디"),
    ("drama", "드라마"),
    ("romance", "로맨스"),
    ("thriller", "스릴러"),
    ("horror", "호러"),
    ("sci-fi", "SF"),
    ("fantasy", "판타지"),
    ("animation", "애니메이션"),
    ("documentary", "다큐멘터리"),
    ("musical", "뮤지컬"),
    ("mystery", "미스터리"),
    )
    genre = models.CharField(max_length=32, choices = GENRE_CHOICES)
    rating = models.CharField(max_length=32)
    time = models.CharField(max_length=32)
    review = models.TextField()
    director = models.CharField(max_length=32)
    actor = models.CharField(max_length=32)
    

myMovieReviews/review/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *
# Create your views here.

def review_list(request):
    movies = Movie.objects.all()
    sort_by = request.GET.get('sort_by')
    
    if sort_by == 'rating':
        movies = sorted(movies, key=lambda movie: float(movie.rating), reverse=True) 
    elif sort_by == 'time':
        movies = sorted(movies, key=lambda movie: int(movie.time)) 
    elif sort_by == 'year':
        movies = sorted(movies, key=lambda movie: int(movie.year), reverse=True)   
    else:
        movies = movies.order_by('title')
    
    movie_durations = []
    for movie in movies:
        total_minutes = int(movie.time)
        hours = total_minutes // 60
        minutes = total_minutes % 60
        movie_durations.append({"hours": hours, "minutes": minutes})
    info_list = zip(movies, movie_durations)
    context = {
        'info_list': info_list,
    }
    return render(request, 'review_list.html', context)

def review_read(request, pk):
    movie = Movie.objects.get(id=pk)
    total_minutes = int(movie.time)
    hours = total_minutes // 60
    minutes = total_minutes % 60
    context = {
        "movie" : movie,
        "hours": hours,
        "minutes": minutes,
    }
    return render(request, "review_read.html", context)

def review_create(request):
    context = {
        'GENRE_CHOICES': Movie.GENRE_CHOICES,
    }
    if request.method == "POST":
        Movie.objects.create (
            title = request.POST["title"],
            year = request.POST["year"],
            genre = request.POST["genre"],
            rating = request.POST["rating"],
            time = request.POST["time"],
            review = request.POST["review"],
            director = request.POST["director"],
            actor = request.POST["actor"],
        )
        return redirect("/review")
    return render(request, "review_create.html", context)

def review_update(request, pk) :
    movie = Movie.objects.get(id=pk)
    context = {
        'GENRE_CHOICES': Movie.GENRE_CHOICES,
        "movie" : movie
    }
    if request.method == "POST" :
        movie.title = request.POST["title"]
        movie.year = request.POST["year"]
        movie.genre = request.POST["genre"]
        movie.rating = request.POST["rating"]
        movie.time = request.POST["time"]
        movie.review = request.POST["review"]
        movie.director = request.POST["director"]
        movie.actor = request.POST["actor"]
        movie.save()
        return redirect(f"/review/{pk}")
    return render(request, "review_update.html", context)

def review_delete (request, pk):
    if request.method == "POST":
        movie = Movie.objects.get(id = pk)
        movie.delete()
    return redirect("/review")

myMovieReviews/review/templates/review_create.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>My Movie reviews</title>
    </head>
    <body>
        <header>
            <h2 class="go_list"><a href="/review/">my<span>Movie</span>reviews</a></h2>
            <a href="/review/create">Add a New review</a>
        </header>
        <hr>
        <form action="/review/create" method="post" class="up_cr_form">
        <div class="up_cr_container">
                {% csrf_token %}
                <h3><span>Movie</span>&nbsp;review 🍿</h3>
                <hr>
                <p>제목 : <input name="title" /></p>
                <p>개봉년도 : <input name="year" /></p>
                <p>
                    장르 :
                    <select name="genre">
                        <option value="------" selected>-----</option>
                        {% for genre_code, genre_label in GENRE_CHOICES %}
                            <option value="{{ genre_code }}">{{ genre_label }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p>별점 : <input name="rating" /></p>
                <p>러닝타임 : <input name="time" /></p>
                <p>리뷰 :</p><textarea name="review" cols="30" rows="10"></textarea>
                <p>감독 : <input name="director" /></p>
                <p>배우 : <input name="actor" /></p>
                <div>
                    <input type="submit" value="save" class="save_btn">
                </div>
            </div>
        </form>
    </body>
</html>

myMovieReviews/review/templates/review_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>My movie reviews</title>
</head>
<body>
    <header>
        <h2>my<span>Movie</span>reviews</h2>
        <a href="/review/create">Add a New review</a>
    </header>
    <hr>
    <div class="list_container">
        <form method="get" action="">
            <label for="sort_by">정렬 기준 : &nbsp;</label>
            <select name="sort_by" id="sort_by">
                <option value="title" {% if request.GET.sort_by == 'title' %}selected{% endif %}>제목 이름순</option>
                <option value="rating" {% if request.GET.sort_by == 'rating' %}selected{% endif %}>별점순</option>
                <option value="year" {% if request.GET.sort_by == 'year' %}selected{% endif %}>최신순</option>
                <option value="time" {% if request.GET.sort_by == 'time' %}selected{% endif %}>상영 시간순</option>
            </select>
            <input type="submit" value="적용">
        </form>
        <div class="movie_container">
            {% for movie, duration in info_list %}
                    <div class="movie_div">
                        <h2><a href="/review/{{ movie.id }}">{{ movie.title }}</a></h2>
                        <p><span>개봉년도</span> {{ movie.year }}</p>
                        <p><span>장르</span> {{ movie.get_genre_display }}</p>
                        <p><span>별점</span> {{ movie.rating }}</p>
                        <p><span>상영시간</span> {{ duration.hours }}시간 {{ duration.minutes }}분</p>
                    </div>
            {% endfor %}
        </div>                
    </div>
</body>
</html>

myMovieReviews/review/templates/review_read.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>My Movie reviews</title>
    </head>
    <body>
        <header>
            <h2 class="go_list"><a href="/review/">my<span>Movie</span>reviews</a></h2>
            <a href="/review/create">Add a New review</a>
        </header>
        <hr>
        <div class="read_container">
            <div class="read_container_header">
                <h1>{{movie.title}}</h1>
                <div class="fix_delete">
                    <a href="/review/{{movie.id}}/update">수정&nbsp;&nbsp;</a>
                    <form action="/review/{{movie.id}}/delete" method="post" onsubmit="return confirmDelete()">
                        {%csrf_token%}
                        <button type="submit" class="delete-button">삭제</button>
                    </form>
                </div>
            </div>
            <div class="read_main">
                <h3><span>개봉년도 </span>{{movie.year}}</h3>
                <h3><span>감독 </span>{{movie.director}}</h3>
                <h3><span>주연 </span>{{movie.actor}}</h3>
                <h3><span>장르 </span>{{ movie.get_genre_display }}</h3>
                <h3><span>별점 </span>{{movie.rating}}</h3>
                <h3><span>러닝타임 </span>
                {% if hours or minutes %}
                    {{ hours }}시간{{ minutes }}분</h3>
                {% endif %}
            </div>
            <div class="read_review">
                <h4>{{movie.review}}</h4>
            </div>
        </div>
        <script>
            function confirmDelete() {
                return confirm("정말 삭제하시겠습니까?");
            }
        </script>
    </body>
</html>

myMovieReviews/review/templates/review_update.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>My Movie reviews</title>
    </head>
    <body>
        <header>
            <h2 class="go_list"><a href="/review/">my<span>Movie</span>reviews</a></h2>
            <a href="/review/create">Add a New review</a>
        </header>
        <hr>
        <form action="/review/{{movie.id}}/update" method="post" class="up_cr_form">
        <div class="up_cr_container">
                {% csrf_token %}
                <h3><span>Movie</span>&nbsp;review 🍿</h3>
                <hr>
                <p>제목 : <input name="title" value="{{movie.title}}"/></p>
                <p>개봉년도 : <input name="year" value="{{movie.year}}"/></p>
                <p>장르 :
                    <select name="genre">
                <option value="------" selected>-----</option>
                {% for genre_code, genre_label in GENRE_CHOICES %}
                    <option value="{{ genre_code }}" {% if genre_code == movie.genre %}selected{% endif %}>{{ genre_label }}</option>
                {% endfor %}
                    </p>
            </select>
                </p>
                <p>별점 : <input name="rating" value="{{movie.rating}}"/></p>
                <p>러닝타임 : <input name="time" value="{{movie.time}}"/></p>
                <p>리뷰 :</p><textarea name="review" cols="30" rows="10">{{movie.review}}</textarea>
                <p>감독 : <input name="director" value="{{movie.director}}"/></p>
                <p>배우 : <input name="actor" value="{{movie.actor}}"/></p>
                <div>
                    <input type="submit" value="save" class="save_btn">
                </div>
            </div>
        </form>
    </body>
</html>