SWIDEA_SITE/server/apps/devtool/urls.py
from django.urls import path
from .views import *

app_name = 'devtools'

urlpatterns = [
    path('list/', devtool_list, name='list'),
    path('create/', create, name ='create'),
    path('delete/<int:pk>/', delete, name="delete"),
    path('update/<int:pk>/', update, name='update'),
    path('detail/<int:pk>/', detail, name='detail'),
]

SWIDEA_SITE/server/apps/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name ='create'),
    path('detail/<int:pk>/', detail, name ='detail'),
    path('delete/<int:pk>/', delete, name ='delete'),
    path('update/<int:pk>/', update, name ='update'),
    path('interest/', interest, name='interest'),
    path('star_list/<int:pk>', star_list, name='star_list'),
    path('star_detail/<int:pk>',star_detail, name='star_detail'),
]

SWIDEA_SITE/server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('devtool/', include('apps.devtool.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/server/apps/devtool/models.py
from django.db import models

class DevTool(models.Model):
    name = models.CharField('이름', max_length=24)
    kind = models.CharField('종류', max_length=24)
    dev_content = models.TextField('개발툴 설명')
    
    def __str__(self):
        return self.name

SWIDEA_SITE/server/apps/posts/models.py
from django.db import models
from apps.devtool.models import DevTool
#from apps.local_users.models import LocalUser

# Create your models here.
class Post(models.Model):
    title = models.CharField('아이디어명', max_length=24)
    photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
    content = models.TextField('아이디어 설명')
    interest = models.IntegerField('아이디어 관심도', default = 0)
    #예상 개발툴
    #user = models.ForeignKey(LocalUser, on_delete=models.CASCADE, verbose_name='작성자')
    devtool = models.ForeignKey(DevTool, on_delete=models.CASCADE, verbose_name='개발툴')
    updated_date = models.DateTimeField('수정일', auto_created=True,auto_now=True)
    star = models.BooleanField('찜하기', default = False)
    
    def __str__(self):
        return self.title

SWIDEA_SITE/server/apps/devtool/forms.py
from django import forms
from .models import DevTool

class DevForm(forms.ModelForm):
    class Meta():
        model = DevTool
        fields = ('__all__')

SWIDEA_SITE/server/apps/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ['title', 'photo', 'content', 'interest', 'devtool']

SWIDEA_SITE/server/apps/devtool/views.py
from django.shortcuts import render, redirect
from .models import DevTool
from .forms import DevForm
# Create your views here.
def devtool_list(request):
    devtools = DevTool.objects.all()
    ctx = {'devtools' : devtools}
    return render(request, 'devtools/devtool_list.html', ctx)

def create(request):
    if request.method == 'GET':
        form = DevForm()
        ctx = {'form' : form}
        return render(request, 'devtools/devtool_create.html', ctx)

    form = DevForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('devtools:list')

def detail(request, pk):
    devtool = DevTool.objects.get(id=pk)
    related_posts = devtool.post_set.all()
    ctx = {'devtool':devtool, 'related_posts':related_posts}
    return render(request,'devtools/devtool_detail.html',ctx)

def delete(request,pk):
    if request.method == 'POST':
        DevTool.objects.get(id=pk).delete()
    return redirect('devtools:list')

def update(request,pk):
    devtool = DevTool.objects.get(id=pk)
    if request.method == 'GET':
        form = DevForm(instance=devtool)
        ctx = {'form': form, 'pk': pk}
        return render(request, 'devtools/devtool_update.html', ctx)
    form = DevForm(request.POST, instance=devtool)
    if form.is_valid():
        form.save()
    return redirect('devtools:detail', pk) #users:list는 pk를 안받음. 내가 억지로 pk 보내니까 오류남

SWIDEA_SITE/server/apps/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post
from django.http import JsonResponse
# Create your views here.
def main(request) :
    posts = Post.objects.all()
    sort = request.GET.get('sort_by')
    
    if sort == 'title':
        posts = posts.order_by('title')
    elif sort == 'pk':
        posts= posts.order_by('pk')
    elif sort == 'updated_date':
        posts = posts.order_by('-pk')
    elif sort == 'interest':
        posts = posts.order_by('-interest')
    elif sort == 'star':
        posts = posts.order_by('-star')
    ctx = {'posts' : posts }
    return render(request, 'posts/post_list.html', ctx)

def create(request) :
    if request.method == 'GET':
        form = PostForm()
        ctx = {'form': form}
        return render(request, 'posts/post_create.html', ctx)
    
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
    return redirect('posts:main')

def detail(request, pk):
    post = Post.objects.get(id=pk)
    ctx = {'post' : post}
    return render(request, 'posts/post_detail.html', ctx)

def delete(request, pk):
    if request.method == 'POST':
        Post.objects.get(id=pk).delete()
    return redirect('posts:main')

def update(request, pk):
    post = Post.objects.get(id=pk)
    if request.method == 'GET':
        form = PostForm(instance=post)
        ctx = {'form':form, 'pk':pk}
        return render(request, 'posts/post_update.html', ctx)
    form = PostForm(request.POST, request.FILES, instance=post)
    if form.is_valid():
        form.save()
    return redirect('posts:detail', pk)

def interest(request):
    if request.method == 'POST':
        pk = request.POST.get('pk', None)
        check = request.POST.get('check', None)
        post = get_object_or_404(Post, id=pk)

        if check == 'increase':
            post_interest = post.interest + 1
        else:
            post_interest = post.interest - 1

        post.interest = post_interest
        post.save()

        return JsonResponse({'interest': post_interest})
    else:
        pass
    
def star_list(request, pk):
    star_toggle = Post.objects.get(id=pk)
    if star_toggle.star:
        star_toggle.star = False
    else:
        star_toggle.star = True
    star_toggle.save()
    return redirect('posts:main')

def star_detail(request, pk):
    star_toggle = Post.objects.get(id=pk)
    if star_toggle.star:
        star_toggle.star = False
    else:
        star_toggle.star = True
    star_toggle.save()
    return redirect('posts:detail', pk)

SWIDEA_SITE/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
  />
  <link rel="stylesheet" href="{% static 'posts/style.css' %}" />
  {%block head%}


  {% endblock %}
</head>
<body>
  <header>
    <a href="/"><p>My <span>SW</span> Idea Manage</p></a>
    <div class="right_header">
      <a href="{% url 'posts:create' %}"><p>아이디어 등록</p></a>
      <a href="/"><p>아이디어 관리</p></a>
      <a href="{% url 'devtools:create' %}"><p>개발툴 등록</p></a>
      <a href="{% url 'devtools:list' %}"><p>개발툴 관리</p></a>
    </div>
  </header>
  <hr>
  <main>
  {%block content%}
      
    
  {%endblock%}
  </main>
</body>

</html>

SWIDEA_SITE/templates/devtools/devtool_create.html
{% extends 'base.html' %}
{%block head%}
  <title>post_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'devtools:create' %}"
    method="post"
    class="create_form"
  >
  <div class="create_header">
    <h2>DevTool Register</h2>
    <p>개발툴 등록 페이지 입니다. 자신이 다룰 수 있는 개발툴을 등록해 보세요.</p>
  </div>
  <div class="create_post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-success">추가하기</button>
  </div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="detail_wrap">
      <div class="detail_div">
          <h1>{{devtool.name}}</h1>
          <p>{{devtool.kind}}</p>
          <p>{{devtool.dev_content}}</p>
      </div>
      <hr>
      <div class="sw"> 만들 수 있는 sw 목록</div>
      {% for rel_post in related_posts %}
      <a href="{% url 'posts:detail' rel_post.pk %}" class="btn btn-success">
        {{rel_post.title}}
      </a>
      {%endfor%}
      <form action="{% url 'devtools:delete' devtool.pk%}" method="POST">
        {%csrf_token%}
        <button type="submit" class="btn btn-danger">삭제</button>
        <a href="{% url 'devtools:list'%}" class="btn btn-primary">목록</a>
        <a href="{% url 'devtools:update' devtool.pk %}" class="btn btn-primary">수정</a>
      </form>
      
  </div>
{% endblock content %}

SWIDEA_SITE/templates/devtools/devtool_list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>Documents</title>
{%endblock%}

{%block content%}
<div class="content-wrapper">
    <hr>
    <!-- 글 목록 -->
    {% for devtool in devtools%}
    <div class="dev_item">
          <p><a href="{% url 'devtools:detail' devtool.pk %}">{{devtool.name}}</a></p>
          <p>{{devtool.kind}}</p>
          <p>{{devtool.dev_content}}</p>
    </div>
    <hr>
    {% endfor %}
  </div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_update.html
{% extends 'base.html' %}

{%block head %}
  <title>post_detail</title>
{%endblock%}


{%block content%}
  <form
    action="{% url 'devtools:update' pk %}"
    method="post"
    class="create_form"
  >
  <div class="create_header">
    <h2>DevTool Detail Update</h2>
    <p>개발툴 세부내용 페이지 입니다. 자신이 다룰 수 있는 개발툴에 대한 상세한 내용을 확인 보세요.</p>
  </div>
  <div class="create_post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-success">수정완료</button>
  </div>
{%endblock%}